CREATE DATABASE AULA_PHP;
USE AULA_PHP;

CREATE TABLE CURSOS (
	ID_CURSO INT NOT NULL AUTO_INCREMENT,
	NOME_CURSO VARCHAR(255) NOT NULL,
	CARGA_HORARIA INT NOT NULL,
	PRIMARY KEY(ID_CURSO)
);

CREATE TABLE ALUNOS(
	ID_ALUNO INT NOT NULL AUTO_INCREMENT,
	NOME_ALUNO VARCHAR(255) NOT NULL,
	DATA_NASCIMENTO VARCHAR(255),
	PRIMARY KEY(ID_ALUNO)
);

CREATE TABLE ALUNOS_CURSOS(
	ID_ALUNO_CURSO INT NOT NULL AUTO_INCREMENT,
	ID_ALUNO INT NOT NULL,
	ID_CURSO INT NOT NULL,
	PRIMARY KEY (ID_ALUNO_CURSO),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

USE AULA_PHP;
CREATE TABLE USUARIOS(
	ID_USUARIO INT AUTO_INCREMENT,
    USUARIO VARCHAR(255)NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UNIQUE(USUARIO)
);


INSERT INTO CURSOS (NOME_CURSO, CARGA_HORARIA)VALUES ("MYSQL" , 10);
INSERT INTO CURSOS VALUES (DEFAULT,"PHP" , 12);
INSERT INTO CURSOS VALUES (DEFAULT,"PHYTHON" , 23);
INSERT INTO CURSOS VALUES (DEFAULT,"C#" , 34);
INSERT INTO CURSOS VALUES (DEFAULT,"C++" , 6);

INSERT INTO ALUNOS VALUES (DEFAULT,"MANOEL RIBEIRO" , "1999-01-02");
INSERT INTO ALUNOS VALUES (DEFAULT,"ROBERTO JAMES" , "1995-01-01");
INSERT INTO ALUNOS VALUES (DEFAULT,"ABEL MARINHO" , "1996-01-03");
INSERT INTO ALUNOS VALUES (DEFAULT,"CARLOS MANTA" , "1997-01-04");
INSERT INTO ALUNOS VALUES (DEFAULT,"BENE DIAS" , "1998-01-05");

/*
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (1,1);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (1,2);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (2,1);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (2,2);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (3,2);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (3,2);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (4,1);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (4,2);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (5,1);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (5,2);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (1,3);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (1,4);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (2,3);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (2,4);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (3,3);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (3,4);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (4,3);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (4,4);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (5,3);
INSERT INTO ALUNOS_CURSOS (ID_CURSO,ID_ALUNO) VALUES (5,4);
*/